name: Flutter CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Static analysis
        run: flutter analyze --no-fatal-infos

      - name: Run unit tests
        run: flutter test

      - name: Build APK (debug)
        run: flutter build apk --debug
